name = "map-worker"
type = "javascript"
account_id = "txHJOXAxDxWdEb5kjL4iAnpBbe8n7np9653nZ4Oy"
workers_dev = true
compatibility_date = "2024-04-23"

[site]
bucket = "./"
entry-point = "workers-site"

[build]
upload.format = "service-worker"
